# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1088, 613)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/img/Search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        # 初始化 QStandardItemModel
        self.model = QtGui.QStandardItemModel()
        self.model.setHorizontalHeaderLabels(["等級", "病患_ID", "名字", "性別", "身高", "病患_LineID"])  # 設置表頭
        
        # 設置模型到 tableView
        self.tableView.setModel(self.model)
        

        # 設置只能選擇整行
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)

        # 添加測試數據
        self.add_table_data()
    
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def add_table_data(self):
        # 新增資料到表格
        data = [
            ["A", "001", " 高翊恩", "男", "172", "n112233"],
            ["B", "002", "李子捷", "男", "168", "j112233"],
            ["C", "003", "朱少謙", "男", "150", "c112233"]
        ]
        
        for row in data:
            items = []
            for item in row:
                table_item = QtGui.QStandardItem(item)
                table_item.setFlags(QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsSelectable)  # 設置為不可編輯
                items.append(table_item)
            self.model.appendRow(items)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText("搜尋...")
